(function(a){var c={cache:{}};c.M=function(b,d){this.$d=b.$d;this.flag=b.flag;this.id=this.$d[0].id;this.text=b.text||true;this.speed=parseInt(b.speed)||5E3;this.hoverStop=b.hoverStop;this.type=b.type||1;this.place=b.place||"fi_tabRB";this.myHtml=b.myHtml||"";this.ptStepX=b.ptStepX||92;this.ptStepY=b.ptStepY||81;this.ptStepX_=b.ptStepX_||4;this.ptStepY_=b.ptStepY_||-1;this.focusData=d;this.clickTabToNav=b.clickTabToNav||false;this._$pointer=this._$desc=this._$transparentOvl=this._$img=this._$titleC=
this._$tabs=this._$tabC=null;this.$d.data("apple",{a:b,b:d});this.init()};c.M.prototype={init:function(){if(this._fiObj=c.cache[this.flag]){this._fiObj.init(this);this.$d.find(".fi_ct").append(this.myHtml);this.spring()}},spring:function(){var b=this,d=function(f){var e=f||0;b.alternation(e);b.autoPlay=setInterval(function(){b.alternation(++e==b.focusData.length?e=0:e)},b.speed)};d();this._$tabs.each(function(f){(function(e,g){g=jQuery(g).click(function(){if(this.className!="now"){clearTimeout(b.autoPlay1);
clearInterval(b.autoPlay);d(e)}b.clickTabToNav&&window.open(b.focusData[e].l);return false});b.hoverStop&&g.mouseenter(function(){clearInterval(b.autoPlay);clearTimeout(b.autoPlay1);this.className!="now"&&b.alternation(e);return false}).mouseleave(function(){clearInterval(b.autoPlay);clearTimeout(b.autoPlay1);var h=e+1==b.focusData.length?0:e+1;b.autoPlay1=window.setTimeout(function(){d(h)},b.speed)})})(f,this)});this._fiObj.initEvts&&this._fiObj.initEvts(this,d)},alternation:function(b){var d=true;
if(this._fiObj.alt)d=this._fiObj.alt(this,b);if(d){this._$img.attr({src:this.focusData[b].p,link:this.focusData[b].l}).css({opacity:0}).stop().animate({opacity:1},500);this._$tabs.filter(".now").removeClass().end().eq(b).addClass("now");this._$titleC.html(this.focusData[b].t);this._$desc&&this._$desc.html(this.focusData[b].t1)}}};a.fn.focusImg=function(b,d){return this.each(function(){b.$d=a(this);new c.M(b,d)})};a.fn.focusImg.Register=function(b,d){c.cache[b]=d}})(jQuery);
$.fn.focusImg.Register("fi01",{init:function(a){var c='<img class="fi_player"/>';c+='<div class="fi_tab '+a.place+'"></div>';c+='<div class="fi_tt"></div>';a.$d.append(c);a._$tabC=a.$d.find(".fi_tab");a._$titleC=a.$d.find(".fi_tt");a._$img=a.$d.find(".fi_player");a.text?a._$titleC.show():a._$titleC.hide();c="";for(var b=0;b<a.focusData.length;b++)c+="<span>"+(b+1)+"</span>";a._$tabC.append(c);a._$tabs=a._$tabC.find("span")},initEvts:function(a){a.$d.click(function(){window.open(a._$img.attr("link"))})}});
$.fn.focusImg.Register("fi02",{init:function(a){var c='<div id="'+a.id+"_"+a.type+'" class="fi02_'+a.type+'">';c+='<img class="fi_player"/>';c+='<div class="fi_ovl"></div>';c+='<div class="fi_tt"></div>';c+='<div class="fi_bg"></div>';c+='<div class="fi_link"></div>';c+='<div class="fi_tab"></div>';c+="</div>";a.$d.append(c);a._$tabC=a.$d.find(".fi_tab");a._$titleC=a.$d.find(".fi_tt");a._$img=a.$d.find(".fi_player");a._$transparentOvl=a.$d.find(".fi_ovl").css("opacity",0.5);c="";for(var b=0;b<a.focusData.length;b++)c+=
"<span>"+(b+1)+"</span>";a._$tabC.append(c);a._$tabs=a._$tabC.find("span")},initEvts:function(a){a.$d.click(function(){window.open(a._$img.attr("link"))})}});
$.fn.focusImg.Register("fi03",{init:function(a){var c='<div class="fi03_'+a.type+'"id="'+a.id+"_"+a.type+'">';c+='<div class="fi_ct">';c+='<img class="fi_player"/><div class="fi_ovl"></div><div class="fi_tt"></div><div class="fi_desc"></div>';c+="</div>";c+='<div class="fi_tab"></div>';c+="</div>";a.$d.append(c);a._$transparentOvl=a.$d.find(".fi_ovl").css("opacity",0.5);a._$img=a.$d.find(".fi_player");a._$titleC=a.$d.find(".fi_tt");a._$desc=a.$d.find(".fi_desc");a._$tabC=a.$d.find(".fi_tab");c="";
for(var b=0;b<a.focusData.length;b++)c+="<span>"+(b+1)+"</span>";a._$tabC.append(c);a._$tabs=a._$tabC.find("span")},initEvts:function(a){a.$d.find(".fi_ct").click(function(){window.open(a._$img.attr("link"))})},alt:function(a){a.type==1&&a._$transparentOvl.css({left:-600}).stop().animate({left:0},200);return true}});
$.fn.focusImg.Register("fi04",{init:function(a){var c='<div class="fi04_'+a.type+'"id="'+a.id+"_"+a.type+'">';c+='<div class="fi_ct">';c+='<img class="fi_player"/><div class="fi_ovl"></div><div class="fi_tt"></div><div class="fi_desc"></div>';c+="</div>";c+='<div class="fi_tab"><span class="fi_pointer"></span><dl></dl></div>';c+="</div>";a.$d.append(c);a._$transparentOvl=a.$d.find(".fi_ovl").css("opacity",0.5);a._$img=a.$d.find(".fi_player");a._$titleC=a.$d.find(".fi_tt");a._$desc=a.$d.find(".fi_desc");
a._$tabC=a.$d.find("dl");a._$pointer=a.$d.find(".fi_pointer");c="";for(var b=0;b<a.focusData.length;b++){a.focusData[b].p1=!a.focusData[b].p1||a.focusData[b].p1==""?a.focusData[b].p:a.focusData[b].p1;c+='<dd><img src="'+a.focusData[b].p1+'"/></dd>'}a._$tabC.append(c).find("img").css("opacity",0.5);a._$tabs=a._$tabC.find("dd")},initEvts:function(a){a.$d.find(".fi_ct").click(function(){window.open(a._$img.attr("link"))});a._$pointer.click(function(){window.open(a._$img.attr("link"))})},alt:function(a,
c){a._$tabs.filter(".now").children().css("opacity",0.5);a._$tabs.eq(c).children().css("opacity",1);switch(a.type){case "1":a._$pointer.stop().animate({left:c*a.ptStepX+a.ptStepX_},200);break;case "2":a._$pointer.stop().animate({top:c*a.ptStepY+a.ptStepY_},200);break}return true}});
$.fn.focusImg.Register("fi05",{init:function(a){var c='<div class="fi05_'+a.type+'"id="'+a.id+"_"+a.type+'">';c+='<div class="fi_ct">';c+='<img class="fi_player"/><div class="fi_ovl"></div><div class="fi_tt"></div>';c+="</div>";c+='<div class="fi_tab"><dl></dl></div>';c+="</div>";a.$d.append(c);a._$transparentOvl=a.$d.find(".fi_ovl").css("opacity",0.5);a._$img=a.$d.find(".fi_player");a._$titleC=a.$d.find(".fi_tt");a._$tabC=a.$d.find("dl");c="";for(var b=0;b<a.focusData.length;b++){a.focusData[b].p1=
!a.focusData[b].p1||a.focusData[b].p1==""?a.focusData[b].p:a.focusData[b].p1;c+='<dd><img src="'+a.focusData[b].p1+'"/><div>'+a.focusData[b].t+"</div></dd>"}a._$tabC.append(c);a._$tabs=a._$tabC.find("dd")},initEvts:function(a){a._$tabs.mouseenter(function(){jQuery(this).addClass("hover")});a._$tabs.mouseleave(function(){jQuery(this).removeClass("hover")});a.$d.find(".fi_ct").click(function(){window.open(a._$img.attr("link"))})},alt:function(a){a._$transparentOvl.css({bottom:-40}).stop().animate({bottom:0},
200);a._$titleC.css({bottom:-24}).stop().animate({bottom:16},200);return true}});
$.fn.focusImg.Register("fi06",{init:function(a){var c='<div class="fi06_'+a.type+' clear"id="'+a.id+"_"+a.type+'">';c+='<div class="fi_ct l">';c+='<a target="_blank"><img class="fi_player"/></a><div class="fi_ovl"></div>';c+='<div class="fi_note"><div class="fi_tt"></div><div class="fi_desc"></div></div>';c+='<span class="fi_btnplay"></span>';c+="</div>";c+='<div class="fi_tab r">';c+='<span class="fi_up"><a href="#" class="fi_btn"></a></span><span class="fi_down"><a href="#" class="fi_btn"></a></span>';c+=
'<div class="fi_tab_"><dl></dl></div>';c+="</div>";c+="</div>";a.$d.html(c);a._$img=a.$d.find(".fi_player");a._$tabC=a.$d.find(".fi_tab dl");a._$titleC=a.$d.find(".fi_tt");a._$desc=a.$d.find(".fi_desc");a._$transparentOvl=a.$d.find(".fi_ovl");a._$note=a.$d.find(".fi_note");a._$tabOvl=a.$d.find(".fi_tab_");c="";for(var b=0;b<a.focusData.length;b++){a.focusData[b].p1=!a.focusData[b].p1||a.focusData[b].p1==""?a.focusData[b].p:a.focusData[b].p1;c+='<dd><img src="'+a.focusData[b].p1+'"/><div class="fi_tt0"><span class="fi_icon"></span>'+
a.focusData[b].t_+'</div><div class="fi_desc0">'+a.focusData[b].t1_+"</div></dd>"}a._$tabC.html(c);a._$tabs=a._$tabC.find("dd")},initEvts:function(a,c){var b=a._$tabC.height()-a._$tabOvl.height();a.$d.find(".fi_btn").click(function(){this.blur();return false});a.$d.find(".r > .fi_up").mousedown(function(){if(a._$tabC.position().top<0)if(!a._$tabC.is(":animated")){clearInterval(a.autoPlay);clearTimeout(a.autoPlay1);a._$tabC.stop().animate({top:"+="+a.ptStepY},200,function(){a.autoPlay1=window.setTimeout(function(){var d=
a._$tabs.filter(".now").index();d=d-1==-1?0:d-1;c(d)},a.speed)})}});a.$d.find(".r > .fi_down").mousedown(function(){if(a._$tabC.position().top>-b)if(!a._$tabC.is(":animated")){clearInterval(a.autoPlay);clearTimeout(a.autoPlay1);a._$tabC.stop().animate({top:"-="+a.ptStepY},200,function(){a.autoPlay1=window.setTimeout(function(){var d=a._$tabs.filter(".now").index();d=d+1==a._$tabs.length?0:d+1;c(d)},a.speed)})}});a.$d.find(".fi_ct").hover(function(){$(this).find(".fi_btnplay").addClass("now")},function(){$(this).find(".fi_btnplay").removeClass("now")}).click(function(){window.open($(this).find("a:eq(0)").attr("href"));
return false})},alt:function(a,c){a._$img.attr("src",a.focusData[c].p).parent().attr("href",a.focusData[c].l);a._$tabs.removeClass("now").eq(c).addClass("now");a._$titleC.html(a.focusData[c].t);a._$desc.html(a.focusData[c].t1);var b=a._$note.width(),d=a._$tabOvl.height();a._$transparentOvl.css("width",0).stop().animate({width:b},200);b=a._$tabs.filter(".now").prevAll().length*a.ptStepY;a._$tabC.height();d=b-(d-a.ptStepY);if(!a._$tabC.is(":animated")){a._$tabC.position().top>-d&&a._$tabC.stop().animate({top:-d},
200);a._$tabC.position().top<-b&&a._$tabC.stop().animate({top:-b},200)}if(a._$tabs[0].className=="now")a._$tabC.is(":animated")||a._$tabC.stop().animate({top:0},200);return false}});
$.fn.focusImg.Register("fi07",{init:function(a){var c='<div class="fi07_'+a.type+'" id="'+a.id+"_"+a.type+'">';c+='<div class="fi_ct">';c+='<div class="fi_list"></div><div class="fi_ovl"></div><div class="fi_tt"></div>';c+="</div>";c+='<div class="fi_tab">';c+='<em class="fi_btn l"><a href="#"></a></em><em class="fi_btn r"><a href="#"></a></em>';c+="</div>";c+="</div>";a.$d.html(c);a._$tabC=a.$d.find(".fi_tab");a._$titleC=a.$d.find(".fi_tt");a._$transparentOvl=a.$d.find(".fi_ovl").css("opacity",0.5);
a._$list=a.$d.find(".fi_list");a._$btnL=a._$tabC.find(".l");a._$btnR=a._$tabC.find(".r");for(var b=c="",d=0;d<a.focusData.length;d++){c+='<span><a href="'+a.focusData[d].l+'"></a></span>';b+='<img src="'+a.focusData[d].p+'"/>'}a._$btnL.after(c);a._$list.html(b);a._$tabs=a._$tabC.find("span");a.ptStepX=a.$d.find(".fi_ct").width()},initEvts:function(a,c){var b=this;a._$tabC.find("a").click(function(){this.blur();return false});a._$btnL.mousedown(function(){var d=a._$tabs.index(a._$tabs.filter(".now")[0]);
if(!(d==0||a._$list.is(":animated"))){clearInterval(a.autoPlay);clearTimeout(a.autoPlay1);b.alt(a,d-1,function(){a.autoPlay1=window.setTimeout(function(){c(d)},a.speed)})}});a._$btnR.mousedown(function(){var d=a._$tabs.index(a._$tabs.filter(".now")[0]);if(!(d==a._$tabs.length-1||a._$list.is(":animated"))){clearInterval(a.autoPlay);clearTimeout(a.autoPlay1);b.alt(a,d+1,function(){a.autoPlay1=window.setTimeout(function(){d=d+2==a._$tabs.length?0:d+2;c(d)},a.speed)})}});a.$d.find(".fi_ct").click(function(){window.open(a._$tabs.filter(".now").find("a").attr("href"))})},
alt:function(a,c,b){a._$tabs.removeClass("now").eq(c).addClass("now");a._$titleC.html(a.focusData[c].t);a._$transparentOvl.css("width",0).stop().animate({width:a.ptStepX},200);a._$list.stop().animate({left:-c*a.ptStepX},200,b);return false}});